import type { ReactNode } from "react";

const whatsappHref = "#contact";

function Icon({ name }: { name: "check" | "arrow" | "pin" | "whatsapp" | "play" | "star" }) {
  const paths = {
    check: <path d="m5 12 4 4L19 6" />,
    arrow: <><path d="M5 12h14" /><path d="m14 7 5 5-5 5" /></>,
    pin: <><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z" /><circle cx="12" cy="10" r="2.5" /></>,
    whatsapp: <><path d="M21 11.5a9 9 0 0 1-13.3 7.9L3 21l1.6-4.6A9 9 0 1 1 21 11.5Z" /><path d="M8.2 7.8c.4 3.5 2.4 5.5 5.9 6.1l1.4-1.4" /></>,
    play: <path d="m9 7 8 5-8 5V7Z" />,
    star: <path d="m12 3 2.6 5.3 5.9.9-4.3 4.1 1 5.8-5.2-2.7-5.2 2.7 1-5.8-4.3-4.1 5.9-.9L12 3Z" />,
  };
  return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}

function CTA({ children, light = false }: { children: ReactNode; light?: boolean }) {
  return <a href={whatsappHref} className={`focus-ring inline-flex items-center justify-center gap-2 rounded-full px-6 py-3.5 text-sm font-semibold ${light ? "bg-white text-ink" : "bg-[#17130d] text-[#d8b35c]"}`}><Icon name="whatsapp" />{children}</a>;
}

function Media({ label, video = false, dark = false }: { label: string; video?: boolean; dark?: boolean }) {
  return <div className={`grid aspect-square place-items-center overflow-hidden rounded-2xl border ${dark ? "border-white/15 bg-white/5 text-white/55" : "border-[#d8c6a0] bg-[#f7f0df] text-[#725b2c]"}`}><div className="flex flex-col items-center gap-3 px-5 text-center">{video ? <span className="grid h-12 w-12 place-items-center rounded-full border border-current"><Icon name="play"/></span> : <span className="text-3xl">＋</span>}<span className="text-[11px] font-semibold uppercase tracking-[.18em]">{label}</span></div></div>;
}

const areas = ["Underarms", "Arms", "Legs", "Bikini line", "Upper lip", "Chin & face"];

export default function Home() {
  return <main>
    <header className="absolute inset-x-0 top-0 z-20 border-b border-white/15 bg-black/20 text-white backdrop-blur-sm"><div className="container-page flex min-h-24 items-center justify-between gap-3 py-4"><a href="#top" className="focus-ring leading-none"><div className="font-display text-[1.65rem] font-semibold tracking-[.04em] text-[#d8b35c] sm:text-3xl">SPIRIT BEAUTY</div><div className="mt-1 text-[8px] uppercase tracking-[.34em] text-[#f0ddaa]">Singapore</div></a><nav className="hidden gap-7 text-[11px] font-semibold uppercase tracking-widest md:flex"><a href="#ipl">IPL</a><a href="#facial">Facial</a><a href="#hair">Hair</a><a href="#visit">Visit</a></nav><a href={whatsappHref} className="rounded-full border border-[#d8b35c]/80 px-4 py-2 text-[11px] font-semibold text-[#f0ddaa]">Book via WhatsApp</a></div></header>

    <section id="top" className="relative min-h-[760px] overflow-hidden bg-[radial-gradient(circle_at_76%_28%,rgba(222,194,126,.20),transparent_26%),linear-gradient(115deg,#2d2927_0%,#635953_48%,#97897f_100%)] text-white"><div className="container-page flex min-h-[760px] items-end pb-16 pt-40 sm:items-center sm:pb-0"><div className="max-w-3xl"><p className="mb-5 text-[11px] font-semibold uppercase tracking-[.25em] text-[#efdca7]">Ang Mo Kio · Singapore</p><h1 className="font-display text-[3.6rem] font-medium leading-[.92] tracking-[-.035em] sm:text-7xl lg:text-[6rem]">Feel smooth.<br/><span className="italic text-[#ecd9cf]">Feel confident.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/80 sm:text-lg">IPL hair removal is our signature focus, supported by facial and hair services in one neighbourhood beauty space.</p><div className="mt-8 flex flex-col gap-3 min-[400px]:flex-row"><CTA light>Enquire on WhatsApp</CTA><a href="#ipl" className="inline-flex items-center justify-center gap-2 px-5 py-3 text-sm font-semibold">Explore IPL <Icon name="arrow"/></a></div></div></div></section>

    <section className="py-20 lg:py-24"><div className="container-page grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">Our salon</p><h2 className="section-title">Your neighbourhood beauty destination.</h2><p className="mt-5 text-sm leading-7 text-ink/60">Your actual storefront photo will go here so customers can recognise Spirit Beauty before they arrive.</p></div><Media label="Upload storefront photo"/></div></section>

    <section id="ipl" className="bg-cream py-24 lg:py-32"><div className="container-page"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">Main promotion</p><h2 className="section-title">Intense Pulsed Light<br/><span className="italic text-cocoa">IPL Hair Removal</span></h2><p className="mt-6 leading-7 text-ink/65">IPL is the signature focus of Spirit Beauty. We explain it simply and lead interested customers directly to consultation and booking.</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3">{areas.map((x,i)=><div key={x} className="rounded-xl border border-sand bg-white p-4"><span className="text-[10px] text-blush">0{i+1}</span><div className="mt-3 font-display text-lg font-semibold">{x}</div></div>)}</div><div className="mt-8"><CTA>Ask about IPL</CTA></div></div><Media label="Upload IPL treatment photo"/></div><div className="mt-12 grid gap-6 md:grid-cols-2"><Media label="Upload IPL video" video/><div className="rounded-2xl bg-[#17130d] p-8 text-white"><p className="text-[11px] font-semibold uppercase tracking-[.2em] text-[#d8b35c]">Our signature focus</p><h3 className="mt-4 font-display text-3xl">IPL made clear and approachable.</h3><div className="mt-6 space-y-4 text-sm text-white/70">{["Clear treatment area choices","Consultation-led recommendation","WhatsApp enquiry one tap away"].map(x=><div key={x} className="flex items-center gap-3"><span className="text-[#d8b35c]"><Icon name="check"/></span>{x}</div>)}</div></div></div></div></section>

    <section id="facial" className="py-24 lg:py-32"><div className="container-page"><p className="eyebrow">Facial care</p><h2 className="section-title">Show the experience.<br/>Show the proof.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-ink/60">This section is prepared for real customer testimonial images and your facial process video.</p><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Media label="Customer testimonial 1"/><Media label="Customer testimonial 2"/><Media label="Customer testimonial 3"/><Media label="Facial process video" video/></div></div></section>

    <section id="hair" className="bg-[#17130d] py-24 text-white lg:py-32"><div className="container-page"><p className="text-[11px] font-semibold uppercase tracking-[.24em] text-[#d8b35c]">Hair promotions</p><h2 className="mt-4 max-w-3xl font-display text-5xl font-medium leading-none sm:text-6xl">Colour & perm promotions.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[["Men's colour","$50","Men's hair colouring promotion."],["Ladies' colour","$90","Ladies' hair colouring promotion."],["Long hair perm","$168","Long hair perm promotion."]].map(([t,p,d])=><article key={t} className="rounded-2xl border border-[#d8b35c]/30 bg-white/5 p-7"><p className="text-xs uppercase tracking-widest text-[#d8b35c]">{t}</p><div className="mt-5 font-display text-5xl">{p}</div><p className="mt-3 text-sm text-white/60">{d}</p></article>)}</div><div className="mt-8 grid gap-5 md:grid-cols-3"><Media label="Men's colour photo" dark/><Media label="Ladies' colour photo" dark/><Media label="Perm result photo" dark/></div><div className="mt-9"><CTA light>Book a hair appointment</CTA></div></div></section>

    <section id="visit" className="py-24 lg:py-32"><div className="container-page grid gap-10 lg:grid-cols-2"><div><p className="eyebrow">How to find us</p><h2 className="section-title">From AMK MRT<br/>to Spirit Beauty.</h2><div className="mt-8 space-y-5">{[["1","Arrive at Ang Mo Kio MRT"],["2","Continue towards Ang Mo Kio Ave 10"],["3","Follow the final route to Spirit Beauty"]].map(([n,t])=><div key={n} className="flex gap-4 border-b border-sand pb-5"><span className="grid h-9 w-9 place-items-center rounded-full bg-cream text-sm font-semibold text-cocoa">{n}</span><div className="pt-2 text-sm font-semibold">{t}</div></div>)}</div><p className="mt-5 text-xs text-ink/45">Exact bus number, walking route and landmarks can be added when you send me the route details.</p></div><Media label="Upload route map / landmark"/></div></section>

    <section className="bg-cream py-24"><div className="container-page"><div className="text-center"><p className="eyebrow">Google reviews</p><h2 className="section-title">What customers say.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[1,2,3].map(i=><article key={i} className="rounded-2xl bg-white p-7 shadow-soft"><div className="flex gap-1 text-[#c79f42]">{[1,2,3,4,5].map(s=><Icon key={s} name="star"/>)}</div><p className="mt-5 text-sm leading-7 text-ink/60">Your real Google review {i} will appear here.</p><p className="mt-5 text-xs font-semibold uppercase tracking-widest text-cocoa">Google customer</p></article>)}</div></div></section>

    <section id="contact" className="bg-sage py-20 text-white"><div className="container-page"><p className="text-[11px] font-semibold uppercase tracking-[.24em] text-white/60">Ready when you are</p><h2 className="mt-4 font-display text-5xl sm:text-6xl">Book your visit.</h2><p className="mt-5 text-sm text-white/70">Ask about IPL, facial or hair promotions through WhatsApp.</p><div className="mt-8"><CTA light>Book via WhatsApp</CTA></div><div className="mt-10 flex gap-4 border-t border-white/15 pt-7"><Icon name="pin"/><div><h3 className="font-display text-2xl">Ang Mo Kio, Singapore</h3><p className="mt-2 text-sm text-white/60">Exact unit and Google Maps link to be added.</p></div></div></div></section>

    <footer className="bg-[#17130d] py-8 text-white"><div className="container-page flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="font-display text-3xl font-semibold tracking-wide text-[#d8b35c]">SPIRIT BEAUTY</div><div className="mt-1 text-[9px] uppercase tracking-[.28em] text-[#f0ddaa]">Singapore</div></div><p className="text-xs text-white/40">© 2026 Spirit Beauty Singapore · Ang Mo Kio</p></div></footer>
    <a href={whatsappHref} className="fixed bottom-5 right-5 z-50 grid h-14 w-14 place-items-center rounded-full bg-[#1fa855] text-white shadow-2xl" aria-label="WhatsApp"><Icon name="whatsapp"/></a>
  </main>;
}
