import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Facial Treatments Ang Mo Kio | Spirit Beauty SG",
  description: "Facial treatments at Spirit Beauty SG in Ang Mo Kio, including personalised consultation, trial pricing and direct WhatsApp booking.",
};

const whatsappHref = "https://wa.me/6586952257?text=Hi%20Spirit%20Beauty%2C%20I%20would%20like%20to%20enquire%20about%20your%20facial%20treatments.";
const mapsHref = "https://www.google.com/maps/search/?api=1&query=Spirit%20Beauty%20Blk%20554%20Ang%20Mo%20Kio%20Ave%2010%20%2301-2044%20Singapore%20560554";

function CTA({ children, light=false }:{children:React.ReactNode;light?:boolean}) {
  return <a href={whatsappHref} target="_blank" rel="noreferrer" className={`inline-flex items-center justify-center rounded-full px-6 py-3.5 text-sm font-semibold transition hover:-translate-y-0.5 ${light?"bg-white text-ink":"bg-[#17130d] text-[#e6c56f]"}`}>{children}</a>;
}

export default function FacialPage(){
  return <main className="overflow-x-hidden bg-[#fffdf9] pb-20 md:pb-0">
    <header className="sticky top-0 z-50 border-b border-white/10 bg-[#17130d]/95 text-white backdrop-blur"><div className="container-page flex min-h-20 items-center justify-between gap-4"><a href="/" className="leading-none"><div className="font-display text-2xl font-semibold tracking-[.04em] text-[#e6c56f]">SPIRIT BEAUTY</div><div className="mt-1 text-[8px] uppercase tracking-[.34em] text-[#f1dfae]">Singapore</div></a><a href="/" className="text-xs font-semibold uppercase tracking-[.16em] text-white/70">Home</a><CTA light>WhatsApp</CTA></div></header>

    <section className="bg-[#17130d] py-24 text-white lg:py-32"><div className="container-page grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="text-[11px] font-semibold uppercase tracking-[.24em] text-[#e6c56f]">Facial Care · Ang Mo Kio</p><h1 className="mt-4 font-display text-[3.4rem] font-medium leading-[.92] tracking-[-.04em] sm:text-7xl">Personalised care<br/><span className="italic text-[#f0ddd3]">for your skin.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/75 sm:text-lg">Our therapist discusses your skin concerns and recommends a suitable treatment approach before proceeding.</p><div className="mt-8"><CTA light>Book a facial consultation</CTA></div></div><div className="rounded-3xl border border-[#e6c56f]/25 bg-white/5 p-8"><p className="text-xs font-semibold uppercase tracking-widest text-[#e6c56f]">Facial Trial</p><div className="mt-3 font-display text-6xl">$88</div><p className="mt-4 text-sm leading-7 text-white/60">Message us to confirm the current trial offer and suitable appointment timing.</p></div></div></section>

    <section className="py-20 lg:py-24"><div className="container-page"><p className="eyebrow">Treatment menu</p><h2 className="section-title">Facial options at Spirit Beauty.</h2><div className="mt-10 grid gap-4 sm:grid-cols-2">{[["Dermal Control Clear-Up Treatment","Targeted facial care based on your current skin concerns and therapist assessment."],["Pico Laser Treatment","A light-based treatment option offered after suitability assessment and consultation."],["AOPT","Advanced Optimal Pulse Technology treatment, subject to skin assessment and suitability."],["Nano Needle EMS Treatment","A treatment combining nano-needle and EMS technology as part of a personalised facial plan."]].map(([t,d],i)=><article key={t} className="rounded-3xl border border-sand bg-white p-7 shadow-soft"><p className="text-xs font-semibold text-cocoa">0{i+1}</p><h3 className="mt-3 font-display text-2xl">{t}</h3><p className="mt-3 text-sm leading-7 text-ink/55">{d}</p></article>)}</div><p className="mt-5 max-w-3xl text-xs leading-6 text-ink/45">Treatment suitability and results vary between individuals. Consultation is recommended before proceeding.</p></div></section>

    <section className="bg-cream py-20 lg:py-24"><div className="container-page grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="eyebrow">What to expect</p><h2 className="section-title">Simple, personalised and easy to book.</h2></div><div className="grid gap-4">{[["01","Tell us your skin concern","Share what you would like help with when you WhatsApp us."],["02","Consultation","Our therapist discusses your skin condition and suitable options."],["03","Confirm your treatment","Choose an available timing and proceed with the agreed treatment plan."]].map(([n,t,d])=><div key={n} className="rounded-2xl bg-white p-6 shadow-sm"><div className="text-xs font-semibold text-cocoa">{n}</div><h3 className="mt-2 font-display text-2xl">{t}</h3><p className="mt-2 text-sm leading-7 text-ink/55">{d}</p></div>)}</div></div></section>

    <section className="py-20 lg:py-24"><div className="container-page grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">Visit Spirit Beauty</p><h2 className="section-title">Blk 554 Ang Mo Kio Ave 10<br/><span className="text-cocoa">#01-2044 · Singapore 560554</span></h2><div className="mt-7 flex flex-col gap-3 min-[420px]:flex-row"><CTA>WhatsApp us</CTA><a href={mapsHref} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center rounded-full border border-cocoa px-6 py-3.5 text-sm font-semibold text-cocoa">Directions</a></div></div><div className="rounded-3xl bg-[#17130d] p-7 text-white"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#e6c56f]">Opening Hours</p><div className="mt-5 space-y-3 text-sm text-white/80"><div className="flex justify-between gap-4"><span>Mon–Wed & Fri</span><strong>1 PM – 8 PM</strong></div><div className="flex justify-between gap-4"><span>Sat–Sun</span><strong>1 PM – 7 PM</strong></div><div className="flex justify-between gap-4"><span>Thursday</span><strong>Closed</strong></div></div><p className="mt-5 border-t border-white/10 pt-5 text-xs leading-5 text-white/55">Last appointment: 7 PM where treatment duration allows. Please WhatsApp us to confirm timing.</p></div></div></section>

    <footer className="bg-[#17130d] py-10 text-white"><div className="container-page flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-display text-2xl text-[#e6c56f]">SPIRIT BEAUTY</div><p className="mt-1 text-xs text-white/50">Facial Care · Ang Mo Kio</p></div><a href="/" className="text-sm font-semibold text-[#f1dfae]">Back to main website →</a></div></footer>
  </main>;
}
