import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SHR IPL Hair Removal Ang Mo Kio | Spirit Beauty SG",
  description: "Explore SHR IPL hair removal at Spirit Beauty SG in Ang Mo Kio. Clear promotional pricing, consultation guidance and direct WhatsApp booking.",
};

const whatsappHref = "https://wa.me/6586952257?text=Hi%20Spirit%20Beauty%2C%20I%20would%20like%20to%20enquire%20about%20SHR%20IPL%20hair%20removal.";
const mapsHref = "https://www.google.com/maps/search/?api=1&query=Spirit%20Beauty%20Blk%20554%20Ang%20Mo%20Kio%20Ave%2010%20%2301-2044%20Singapore%20560554";

const prices = [["Upper Lip", "$18"],["Underarm", "$38"],["Face", "$48"],["Brazilian", "$48"],["Half Leg", "$68"]];

const faqs = [
  ["Is SHR IPL hair removal a one-time treatment?", "No. Hair grows in different cycles, so SHR IPL hair reduction requires a course of multiple sessions rather than a single treatment. A series of sessions helps target hairs during different stages of the growth cycle. Results vary between individuals."],
  ["How many sessions will I need for long-term hair reduction?", "Many clients may require around 10–12 sessions, but there is no fixed number for everyone. The number of sessions depends on factors such as the treatment area, hair thickness and colour, skin tone, hair-growth cycle and your individual response to treatment. Maintenance sessions may also be needed over time."],
  ["How soon can I see results?", "Some clients notice a visible reduction in hair growth after the first 1–2 sessions. However, results vary from person to person, and completing the recommended treatment course is important for the best long-term result."],
  ["What should I avoid during my SHR IPL treatment course?", "Avoid waxing, plucking, epilating or any other method that removes the hair from the root during your treatment course, as SHR IPL needs the hair follicle to be present. Shaving is generally the preferred method between sessions when needed. Please follow the therapist’s preparation and aftercare instructions for your treatment area."],
  ["Is Brazilian SHR IPL available?", "Yes. Brazilian is one of our popular treatment areas and is currently listed at $48 under the promotion shown on this page."],
  ["Do I need a consultation?", "Consultation is recommended so we can discuss the treatment area, skin and hair characteristics, expectations and suitability before proceeding."],
  ["How do I book?", "Tap the WhatsApp button, tell us your treatment area and preferred timing, and we will reply with availability."],
];

function CTA({ children, light = false }: { children: React.ReactNode; light?: boolean }) {
  return <a href={whatsappHref} target="_blank" rel="noreferrer" className={`inline-flex items-center justify-center rounded-full px-6 py-3.5 text-sm font-semibold transition hover:-translate-y-0.5 ${light ? "bg-white text-ink" : "bg-[#17130d] text-[#e6c56f]"}`}>{children}</a>;
}

export default function IPLPage() {
  return (
    <main className="overflow-x-hidden bg-[#fffdf9] pb-20 md:pb-0">
      <header className="sticky top-0 z-50 border-b border-white/10 bg-[#17130d]/95 text-white backdrop-blur"><div className="container-page flex min-h-20 items-center justify-between gap-4"><a href="/" className="leading-none"><div className="font-display text-2xl font-semibold tracking-[.04em] text-[#e6c56f]">SPIRIT BEAUTY</div><div className="mt-1 text-[8px] uppercase tracking-[.34em] text-[#f1dfae]">Singapore</div></a><a href="/" className="text-xs font-semibold uppercase tracking-[.16em] text-white/70">Home</a><CTA light>WhatsApp</CTA></div></header>

      <section className="relative isolate min-h-[690px] overflow-hidden bg-[#17130d] text-white"><img src="/media/ipl-brazilian.webp" alt="SHR IPL result at Spirit Beauty" className="absolute inset-0 -z-20 h-full w-full object-cover object-center" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black/90 via-black/70 to-black/35" /><div className="container-page flex min-h-[690px] items-end pb-14 pt-24 sm:items-center sm:pb-0"><div className="max-w-3xl"><p className="text-[11px] font-semibold uppercase tracking-[.24em] text-[#f1dfae]">SHR IPL · Ang Mo Kio</p><h1 className="mt-5 font-display text-[3.5rem] font-medium leading-[.9] tracking-[-.04em] sm:text-7xl lg:text-[5.8rem]">Smoother skin,<br /><span className="italic text-[#f0ddd3]">clearer pricing.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/80 sm:text-lg">Straightforward SHR IPL hair-removal promotions with direct WhatsApp booking, consultation guidance and no hidden-cost messaging.</p><div className="mt-8 flex flex-col gap-3 min-[420px]:flex-row"><CTA light>Book SHR IPL</CTA><a href="#prices" className="inline-flex items-center justify-center rounded-full border border-white/35 px-6 py-3.5 text-sm font-semibold">See prices ↓</a></div></div></div></section>

      <section id="prices" className="py-20 lg:py-24"><div className="container-page"><div className="max-w-2xl"><p className="eyebrow">Current SHR IPL promotion</p><h2 className="section-title">Choose your treatment area.</h2><p className="mt-4 text-sm leading-7 text-ink/60">Promotional prices shown below are for the listed treatment areas. Message us to confirm the current offer and appointment timing.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{prices.map(([area, price]) => <article key={area} className={`rounded-2xl border p-6 ${area === "Brazilian" ? "border-[#b98b2e] bg-[#17130d] text-white" : "border-sand bg-white"}`}><p className={`text-xs font-semibold uppercase tracking-widest ${area === "Brazilian" ? "text-[#e6c56f]" : "text-cocoa"}`}>{area}{area === "Brazilian" ? " · Popular" : ""}</p><div className="mt-4 font-display text-4xl">{price}</div></article>)}</div><div className="mt-8"><CTA>Check availability</CTA></div></div></section>

      <section className="bg-cream py-20 lg:py-24"><div className="container-page grid gap-10 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><p className="eyebrow">What to expect</p><h2 className="section-title">Simple from enquiry to appointment.</h2><div className="mt-8 space-y-4">{[["01","Message us","Tell us the treatment area you are interested in."],["02","Check suitability","We discuss the area, skin and hair characteristics, and treatment expectations."],["03","Confirm timing","Choose an available appointment and confirm directly through WhatsApp."]].map(([n,t,d]) => <div key={n} className="rounded-2xl bg-white p-6 shadow-sm"><div className="text-xs font-semibold text-cocoa">{n}</div><h3 className="mt-2 font-display text-2xl">{t}</h3><p className="mt-2 text-sm leading-6 text-ink/55">{d}</p></div>)}</div></div><figure className="overflow-hidden rounded-3xl border border-sand bg-white shadow-soft"><img src="/media/ipl-brazilian.webp" alt="Brazilian SHR IPL before and after" className="w-full object-cover" /><figcaption className="px-5 py-4 text-xs font-semibold uppercase tracking-widest text-cocoa">Real client result · Brazilian IPL</figcaption></figure></div></section>

      <section className="py-20 lg:py-24"><div className="container-page"><div className="max-w-2xl"><p className="eyebrow">Why Spirit Beauty</p><h2 className="section-title">Clear, local and easy to book.</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{["Shaving and treatment gel included","Unlimited shots for the treatment area","Fast, targeted treatment","Helps reduce the appearance of ingrown hairs","No hard selling","No hidden costs"].map(item => <div key={item} className="rounded-2xl border border-sand bg-white p-5 text-sm font-semibold">✓ {item}</div>)}</div><p className="mt-5 text-xs leading-5 text-ink/45">Hair-reduction results and treatment experience vary between individuals. Consultation is recommended.</p></div></section>

      <section className="bg-[#17130d] py-20 text-white lg:py-24"><div className="container-page grid gap-8 lg:grid-cols-[1fr_.75fr] lg:items-center"><div><p className="text-[11px] font-semibold uppercase tracking-[.24em] text-[#e6c56f]">Visit us</p><h2 className="mt-4 font-display text-4xl sm:text-5xl">Blk 554 Ang Mo Kio Ave 10<br /><span className="text-[#e6c56f]">#01-2044 · Singapore 560554</span></h2><div className="mt-7 flex flex-col gap-3 min-[420px]:flex-row"><CTA light>WhatsApp us</CTA><a href={mapsHref} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center rounded-full border border-white/25 px-6 py-3.5 text-sm font-semibold">Get directions</a></div></div><div className="rounded-3xl border border-white/10 bg-white/5 p-7 text-sm leading-7 text-white/70">Appointment is recommended. When messaging us, include the treatment area you are interested in so we can respond faster.</div></div></section>

      <section className="py-20 lg:py-24"><div className="container-page max-w-4xl"><p className="eyebrow">SHR IPL FAQ</p><h2 className="section-title">Common questions before your treatment.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-ink/60">What to expect, how many sessions may be needed, when results may become visible and how to care for the treatment area between appointments.</p><div className="mt-10 divide-y divide-sand border-y border-sand">{faqs.map(([q,a]) => <details key={q} className="group py-5"><summary className="cursor-pointer list-none pr-8 font-semibold">{q}<span className="float-right text-cocoa">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-7 text-ink/60">{a}</p></details>)}</div><div className="mt-8"><CTA>Ask us on WhatsApp</CTA></div></div></section>

      <footer className="bg-[#17130d] py-10 text-white"><div className="container-page flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-display text-2xl text-[#e6c56f]">SPIRIT BEAUTY</div><p className="mt-1 text-xs text-white/50">SHR IPL Hair Removal · Ang Mo Kio</p></div><a href="/" className="text-sm font-semibold text-[#f1dfae]">Back to main website →</a></div></footer>

      <div className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-2 gap-2 border-t border-sand bg-white/95 p-3 backdrop-blur md:hidden"><a href={whatsappHref} target="_blank" rel="noreferrer" className="rounded-full bg-[#25D366] px-4 py-3 text-center text-sm font-semibold text-white">WhatsApp</a><a href={mapsHref} target="_blank" rel="noreferrer" className="rounded-full bg-[#17130d] px-4 py-3 text-center text-sm font-semibold text-[#e6c56f]">Directions</a></div>
    </main>
  );
}
