import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hair Colour Promotions Ang Mo Kio | Spirit Beauty SG",
  description: "Hair colour, highlight and balayage promotions at Spirit Beauty SG in Ang Mo Kio. Direct WhatsApp enquiries and transparent promotional pricing.",
};

const whatsappHref = "https://wa.me/6586952257?text=Hi%20Spirit%20Beauty%2C%20I%20would%20like%20to%20enquire%20about%20your%20hair%20colour%20promotion.";
const mapsHref = "https://www.google.com/maps/search/?api=1&query=Spirit%20Beauty%20Blk%20554%20Ang%20Mo%20Kio%20Ave%2010%20%2301-2044%20Singapore%20560554";

function CTA({ children, light=false }:{children:React.ReactNode;light?:boolean}) {
  return <a href={whatsappHref} target="_blank" rel="noreferrer" className={`inline-flex items-center justify-center rounded-full px-6 py-3.5 text-sm font-semibold transition hover:-translate-y-0.5 ${light?"bg-white text-ink":"bg-[#17130d] text-[#e6c56f]"}`}>{children}</a>;
}

export default function HairPage(){
  return <main className="overflow-x-hidden bg-[#fffdf9] pb-20 md:pb-0">
    <header className="sticky top-0 z-50 border-b border-white/10 bg-[#17130d]/95 text-white backdrop-blur"><div className="container-page flex min-h-20 items-center justify-between gap-4"><a href="/" className="leading-none"><div className="font-display text-2xl font-semibold tracking-[.04em] text-[#e6c56f]">SPIRIT BEAUTY</div><div className="mt-1 text-[8px] uppercase tracking-[.34em] text-[#f1dfae]">Singapore</div></a><a href="/" className="text-xs font-semibold uppercase tracking-[.16em] text-white/70">Home</a><CTA light>WhatsApp</CTA></div></header>

    <section className="relative isolate min-h-[680px] overflow-hidden bg-[#17130d] text-white"><img src="/media/hair-bob.webp" alt="Hair colour result at Spirit Beauty" className="absolute inset-0 -z-20 h-full w-full object-cover object-center"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black/90 via-black/70 to-black/35"/><div className="container-page flex min-h-[680px] items-end pb-14 pt-24 sm:items-center sm:pb-0"><div className="max-w-3xl"><p className="text-[11px] font-semibold uppercase tracking-[.24em] text-[#f1dfae]">Hair Colour · Ang Mo Kio</p><h1 className="mt-5 font-display text-[3.4rem] font-medium leading-[.92] tracking-[-.04em] sm:text-7xl lg:text-[5.5rem]">Fresh colour.<br/><span className="italic text-[#f0ddd3]">Fresh look.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/80 sm:text-lg">Straightforward hair-colour promotions with direct WhatsApp quotations for whole-head colour, highlights and balayage.</p><div className="mt-8 flex flex-col gap-3 min-[420px]:flex-row"><CTA light>Ask for a hair quote</CTA><a href="#prices" className="inline-flex items-center justify-center rounded-full border border-white/35 px-6 py-3.5 text-sm font-semibold">See promotions ↓</a></div></div></div></section>

    <section id="prices" className="py-20 lg:py-24"><div className="container-page"><p className="eyebrow">Hair promotions</p><h2 className="section-title">Clear promotional pricing.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{[["Men's Whole Hair Colour","$50"],["Ladies' Whole Hair Colour","$90"],["Highlight / Balayage","From $310"]].map(([t,p])=><article key={t} className="rounded-3xl border border-sand bg-white p-7 shadow-soft"><p className="text-xs font-semibold uppercase tracking-widest text-cocoa">{t}</p><div className="mt-4 font-display text-5xl">{p}</div></article>)}</div><p className="mt-5 max-w-3xl text-xs leading-6 text-ink/45">Final pricing may vary for extra-long or very thick hair, previous colour history, bleaching requirements and additional product usage. Send us a clear photo for a more accurate quotation.</p><div className="mt-8"><CTA>Send hair photo on WhatsApp</CTA></div></div></section>

    <section className="bg-[#17130d] py-20 text-white lg:py-24"><div className="container-page grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><figure className="overflow-hidden rounded-3xl border border-white/10 bg-white/5"><img src="/media/hair-bob.webp" alt="Spirit Beauty hair colour work" className="aspect-[4/5] h-full w-full object-cover"/><figcaption className="px-5 py-4 text-xs font-semibold uppercase tracking-widest text-[#e6c56f]">Spirit Beauty hair colour work</figcaption></figure><div><p className="text-[11px] font-semibold uppercase tracking-[.24em] text-[#e6c56f]">How to get a quotation</p><h2 className="mt-4 font-display text-4xl sm:text-5xl">Send us two photos.</h2><div className="mt-7 space-y-4 text-sm leading-7 text-white/75"><p>1. A clear photo of your current hair in natural lighting.</p><p>2. A reference photo showing the colour or balayage result you want.</p><p>We will advise what may be achievable and whether bleaching or multiple steps could be required.</p></div><div className="mt-8"><CTA light>Get a WhatsApp quotation</CTA></div></div></div></section>

    <section className="py-20 lg:py-24"><div className="container-page"><p className="eyebrow">Before your appointment</p><h2 className="section-title">A few useful notes.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{[["Colour history","Tell us about previous box dye, henna, bleach or dark colour so we can assess more accurately."],["Hair condition","Very dry, fragile or heavily processed hair may need a more conservative colour plan."],["Reference result","Hair colour can look different depending on lighting, starting base and hair condition. Reference photos help us understand your target."]].map(([t,d])=><article key={t} className="rounded-2xl bg-cream p-6"><h3 className="font-display text-2xl">{t}</h3><p className="mt-3 text-sm leading-7 text-ink/55">{d}</p></article>)}</div></div></section>

    <section className="bg-cream py-20 lg:py-24"><div className="container-page grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">Visit Spirit Beauty</p><h2 className="section-title">Blk 554 Ang Mo Kio Ave 10<br/><span className="text-cocoa">#01-2044 · Singapore 560554</span></h2><div className="mt-7 flex flex-col gap-3 min-[420px]:flex-row"><CTA>WhatsApp us</CTA><a href={mapsHref} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center rounded-full border border-cocoa px-6 py-3.5 text-sm font-semibold text-cocoa">Directions</a></div></div><div className="rounded-3xl bg-[#17130d] p-7 text-white"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#e6c56f]">Opening Hours</p><div className="mt-5 space-y-3 text-sm text-white/80"><div className="flex justify-between gap-4"><span>Mon–Wed & Fri</span><strong>1 PM – 8 PM</strong></div><div className="flex justify-between gap-4"><span>Sat–Sun</span><strong>1 PM – 7 PM</strong></div><div className="flex justify-between gap-4"><span>Thursday</span><strong>Closed</strong></div></div><p className="mt-5 border-t border-white/10 pt-5 text-xs leading-5 text-white/55">Last appointment: 7 PM where service duration allows. Please WhatsApp us to confirm timing.</p></div></div></section>

    <footer className="bg-[#17130d] py-10 text-white"><div className="container-page flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-display text-2xl text-[#e6c56f]">SPIRIT BEAUTY</div><p className="mt-1 text-xs text-white/50">Hair Colour · Ang Mo Kio</p></div><a href="/" className="text-sm font-semibold text-[#f1dfae]">Back to main website →</a></div></footer>
  </main>;
}
